using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using com.Bynonco.LIMS.Model.Enum;

namespace com.Bynonco.LIMS.BLL.Business
{
    /// <summary>
    /// 继承该接口的类命名规则,客户名称拼音首字母大学+Customer
    /// </summary>
    public interface ICutomer
    {
        /// <summary>
        /// 系统名称
        /// </summary>
        /// <returns></returns>
        string GetSystemName();

        /// <summary>
        /// 学校拼音首字母
        /// </summary>
        /// <returns></returns>
        string GetCode();

        /// <summary>
        /// 学校名称
        /// </summary>
        /// <returns></returns>
        string GetSchoolName();

        /// <summary>
        /// 登陆是否显示记住密码
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        bool GetIsLoginShowRememberMe();
        /// <summary>
        /// 前台首页
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        string GetHomeIndex(string xpath);
        /// <summary>
        /// 前台-Banner
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        string GetHomeBanner(string xpath);
        /// <summary>
        /// 前台-Menu
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        string GetHomeMenu();
        /// <summary>
        /// 前台-Skin
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        string GetHomeSkins(string xpath);
        /// <summary>
        /// 前台-Footer
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        string GetHomeFooter(string xpath);
        /// <summary>
        /// 前台引用模板Xpath
        /// </summary>
        /// <param name="xpath"></param>
        /// <returns></returns>
        string GetHomeLayoutXPath(string xpath);
        /// <summary>
        /// 个人中心-仪器设备--搜索框
        /// </summary>
        /// <returns></returns>
        string GetEquipmentManageSearch();
        /// <summary>
        /// 仪器设备--大图展示
        /// </summary>
        /// <returns></returns>
        string GetEquipmentIconListPage();
        /// <summary>
        /// 前台-仪器展示页面
        /// </summary>
        /// <returns></returns>
        string GetEquipmentShowList();
        /// <summary>
        /// 前台-仪器展示页面分类查看项
        /// </summary>
        /// <returns></returns>
        string GetEquipmentShowListConditionSeach();
        /// <summary>
        /// 仪器详情
        /// </summary>
        /// <returns></returns>
        string GetEquipmentShow();
        /// <summary>
        /// 仪器详情-顶部信息
        /// </summary>
        /// <returns></returns>
        string GetEquipmentShowTopInfo();
        /// <summary>
        /// 仪器详情-基本信息
        /// </summary>
        /// <returns></returns>
        string GetEquipmentShowBasic();
        /// <summary>
        /// 仪器负责人显示名称
        /// </summary>
        /// <returns></returns>
        string GetEquipmentDirectorName();
        /// <summary>
        /// 仪器联系人显示名称
        /// </summary>
        /// <returns></returns>
        string GetEquipmentLinkMenName();
        /// <summary>
        /// 是否能否编辑样品编号
        /// </summary>
        /// <returns></returns>
        bool JudgeIsEnableEditSampleAppyNumber();
        /// <summary>
        /// 校内用户送样单
        /// </summary>
        /// <returns></returns>
        string GetSampleInnerApplyViewName();
        /// <summary>
        /// 校内外用户送样单
        /// </summary>
        /// <returns></returns>
        string GetSampleInnerOrOuterApplyViewName();
        string GetSampleInfoViewName();
        /// <summary>
        /// 审核是否需要输入预计完成时间
        /// </summary>
        /// <returns></returns>
        bool JudgeIsNeedInputSamplePredictResultTimeWhenAudit();
        /// <summary>
        /// 审核是否需要选择测试人
        /// </summary>
        /// <returns></returns>
        bool JudgeIsNeedSelectSampleTesterWhenAudit();
        /// <summary>
        /// 获取送样未审核列表排序名
        /// </summary>
        /// <returns></returns>
        string GetUnAuditSampleListSortName();
        /// <summary>
        /// 获取送样未审核列表排每页显示的记录
        /// </summary>
        /// <returns></returns>
        int GetUnAuditSampleListPageSize();
        /// <summary>
        /// 项目名称显示
        /// </summary>
        /// <returns></returns>
        string GetSubjectProjectShowName();
        /// <summary>
        /// 组织机构名称
        /// </summary>
        /// <returns></returns>
        string GetLabOrganizationName();
        /// <summary>
        /// 是否预约展示样品编号、样品数
        /// </summary>
        /// <returns></returns>
        bool GetIsShowAppointmentSampleInfo();
        /// <summary>
        /// 是否设备管理员绑定
        /// </summary>
        /// <returns></returns>
        bool GetIsBindEquipmentAdminUser();
        /// <summary>
        /// 是否设备联系人绑定
        /// </summary>
        /// <returns></returns>
        bool GetIsBindEquipmentLinkUser();
        /// <summary>
        /// 是否注册用户上传头像
        /// </summary>
        /// <returns></returns>
        bool GetIsRegistUserUploadRelativePic();
        /// <summary>
        /// 是否注册用户上传证件附件
        /// </summary>
        /// <returns></returns>
        bool GetIsRegistUserUploadCertificatePhoto();
        /// <summary>
        /// 是否注册用户增加动物实验伦理编号、实验名称
        /// </summary>
        /// <returns></returns>
        bool GetIsRegistUserAnimalExperimentInfo();
        /// <summary>
        /// 是否注册用户显示南京医科大提示信息
        /// </summary>
        /// <returns></returns>
        bool GetIsNJYKDRegistNoteInfo();
        /// <summary>
        /// 是否注册导师用户显示经费卡号
        /// </summary>
        /// <returns></returns>
        bool GetIsRegistTutorMoneyCard();
       
        /// <summary>
        /// 是否存款自动打印doc
        /// </summary>
        bool GetIsDepositAutoPrintDoc();
        /// <summary>
        /// 是否存款上传附件
        /// </summary>
        /// <returns></returns>
        bool GetIsDepositPhoto();
        /// <summary>
        /// 是否存款上传附件(预审通过才显示)
        /// </summary>
        /// <returns></returns>
        bool GetIsDepositPhotoAfterPreAudit();
        /// <summary>
        /// 是否存款分预审（预审后上传凭证）+审核，预审自动审核通过
        /// </summary>
        /// <returns></returns>
        bool GetIsDepositPhotoAutoPreAuditPass();
        /// <summary>
        /// 是否存款上传附件(必填)
        /// </summary>
        /// <returns></returns>
        bool GetIsDepositPhotoRequired();
        /// <summary>
        /// 是否存款检测人(必填)
        /// </summary>
        /// <returns></returns>
        bool GetIsDepositTesterRequired();
        /// <summary>
        /// 是否用户增加特权卡字段
        /// </summary>
        /// <returns></returns>
        bool GetIsRegistryCard();
        /// <summary>
        /// 是否用户增加所属团队字段
        /// </summary>
        /// <returns></returns>
        bool GetIsUserWorkTeam();
        /// <summary>
        /// 是否前台展示最新设备
        /// </summary>
        /// <returns></returns>
        bool GetIsShowNewEquipmetn();
        /// <summary>
        /// 是否首页展示最新设备分类
        /// </summary>
        /// <returns></returns>
        bool GetIsShowEquipmetnCategoryForHome();
        /// <summary>
        /// 是否首页菜单展示搜索框
        /// </summary>
        /// <returns></returns>
        bool GetIsShowMenuEquipmetnSearch();
        /// <summary>
        /// 是否展示扣费统计计费时长字段 
        /// </summary>
        /// <returns></returns>
        bool GetIsShowCostDeductCalcDurationStatistics();
        /// <summary>
        /// 编辑使用记录是否自动计算费用
        /// </summary>
        /// <returns></returns>
        bool GetIsAutoCalUsedConfirmFee();
        /// <summary>
        /// 是否只有管理才能扣费账户为负的使用记录
        /// </summary>
        /// <returns></returns>
        bool GetIsOnlySuperAdminEnableHandleMinuseCostDeduct();
        /// <summary>
        /// 是否可以自己输入机时预约时间
        /// </summary>
        /// <returns></returns>
        bool GetIsEnableInputAppointmentTimes();
        /// <summary>
        /// 是否使用开放基金扣费模式
        /// </summary>
        /// <returns></returns>
        bool GetIsOpenFundCostDeduct();
        /// <summary>
        /// 管理员可否改约非本人的机时预约
        /// </summary>
        /// <returns></returns>
        bool GetIsAdminEnableChangeAppointmentOfOtherUser();
        /// <summary>
        /// 管理员可否取消非本人的机时预约
        /// </summary>
        /// <returns></returns>
        bool GetIsAdminEnableCancelAppointmentOfOtherUser();

        /// <summary>
        /// 是否文章列表显示一列
        /// </summary>
        /// <returns></returns>
        bool GetIsArticleShowOneColumn();
        /// <summary>
        /// 是否文章内容显示一列
        /// </summary>
        /// <returns></returns>
        bool GetIsArticleShowListOneColumn();

        /// <summary>
        /// 是否开放实验动物模块
        /// </summary>
        /// <returns></returns>
        bool GetIsOpenAnimalModules();

        /// <summary>
        /// 是否显示首页菜单仪器组织
        /// </summary>
        /// <returns></returns>
        bool GetIsShowMemuOrganizationList();

        /// <summary>
        /// 是否首页菜单更多改为more
        /// </summary>
        /// <returns></returns>
        bool GetIsMainPageChangeToMore();

        /// <summary>
        /// 高级搜索页面
        /// </summary>
        /// <returns></returns>
        string GetEquipmentSearchAdvanced();
        /// <summary>
        /// 是否显示设备送样检测项目查询条件
        /// </summary>
        /// <returns></returns>
        bool GetIsShowEquipmentSampleItemSearch();
        /// <summary>
        /// 填写送样申请单，检测条件及要求是否必填
        /// </summary>
        /// <returns></returns>
        bool GetIsSampleItemTestConditionRequired();
        /// <summary>
        /// 获取送样状态名称
        /// </summary>
        /// <returns></returns>
        string GetSampleApplyStatusName(SampleApplyStatus sampleApplyStatus);
        /// <summary>
        /// 获取送样收费状态名称
        /// </summary>
        string GetSampleChargeStatusName(Model.Enum.SampleApplyStatus sampleApplyStatus, SampleChargeStatus sampleChargeStatus);
        /// <summary>
        /// 是否提供用户注册表下载
        /// </summary>
        /// <returns></returns>
        bool GetIsRegisterDoc();
        /// <summary>
        /// 获取是否进行动物自动扣费
        /// </summary>
        /// <returns></returns>
        bool GetIsStartAnimalModule();
        /// <summary>
        /// 机时预约是否显示样品材料
        /// </summary>
        /// <returns></returns>
        bool GetIsShowAppointmentSampleStuff();
        /// <summary>
        /// 机时预约是否显示样品尺寸
        /// </summary>
        /// <returns></returns>
        bool GetIsShowAppointmentSampleSize();
        /// <summary>
        /// 机时预约是否显示样品目的
        /// </summary>
        /// <returns></returns>
        bool GetIsShowAppointmentSampleTarget();
        /// <summary>
        /// 机时预约样品数是否必填
        /// </summary>
        /// <returns></returns>
        bool GetIsAppointmentSampleAmountRequired();
        /// <summary>
        /// 机时预约设备管理员是否需要关联样品申请单
        /// </summary>
        /// <returns></returns>
        bool GetIsAppointmentEqAdminNeedSelectSampleApply();
        /// <summary>
        /// 个人中心菜单增加“设备预约”跳转首页(浙大需求)
        /// </summary>
        /// <returns></returns>
        bool GetIsShowEquipmentMenuRedirectToHome();
        /// <summary>
        /// 普通存款-样品编号显示名称
        /// </summary>
        /// <returns></returns>
        string GetDepositSamplyNoDisplayName();
        /// <summary>
        /// 是否用户增加课题项目信息编辑
        /// </summary>
        /// <returns></returns>
        bool GetIsUserManageSubjectProject();

        /// <summary>
        /// 是否普通存款要求设备费用明细
        /// </summary>
        /// <returns></returns>
        bool GetIsDepositRecordEquipmentRequired();

        /// <summary>
        /// 发送消息的同时是否发送给导师
        /// </summary>
        /// <returns></returns>
        bool GetIsSendMessageToTutorSameTime();
        /// <summary>
        /// 超级管理员是否只显示自己管理的设备，而非全部设备
        /// </summary>
        /// <returns></returns>
        bool GetIsSuperAdminOnlyShowAdminEqList();

        /// <summary>
        /// 是否手工扣费需要学生卡号验证
        /// </summary>
        /// <returns></returns>
        bool IsManualCostDeductByCard();

        /// <summary>
        /// 是否编辑仪器价格单位
        /// </summary>
        /// <returns></returns>
        bool GetIsShowEquipmentPriceUnit();

        /// <summary>
        /// 是否检查登录状态显示交流园地
        /// </summary>
        /// <returns></returns>
        bool GetIsOriginalCheckLogin();
        /// <summary>
        /// 送样审核是否显示提交按钮
        /// </summary>
        /// <returns></returns>
        bool GetIsShowSampleSubmitOpWhenAuditing();
        /// <summary>
        ///填写送样申请单是否显示价格 
        /// </summary>
        /// <returns></returns>
        bool GetIsHidePredictPriceWhenInputSampleApply();
        /// <summary>
        /// 查看送样单详细信息是否显示扣费信息
        /// </summary>
        /// <returns></returns>
        bool GetIsHideChargeInfoWhenViewSampleApplyDetail();

        /// <summary>
        /// 获取成果管理科研项目来源
        /// </summary>
        /// <returns></returns>
        string GetAchievementSubjectComeCode();

        /// <summary>
        /// 获取默认动物环境质量编号
        /// </summary>
        /// <returns></returns>
        string GetDefaultAnimalEnviromentQuatityNo();
        /// <summary>
        /// 前台菜单是否显示免税设备
        /// </summary>
        /// <returns></returns>
        bool GetIsShowDutyFreeEquipment();
        /// <summary>
        /// 首页行二中是否显示长度为153
        /// </summary>
        /// <returns></returns>
        bool GetIsShowSecondLineCenter153();
        /// <summary>
        /// 设备维修是否绑定维修单位
        /// </summary>
        /// <returns></returns>
        bool GetIsLoadRepariUnit();
        /// <summary>
        /// 设备编辑是否显示北京交通大学附加字段
        /// </summary>
        /// <returns></returns>
        bool GetIsShowBJJTDXCol();
        /// <summary>
        /// 获取前台页面加载TopLogin页面
        /// </summary>
        /// <returns></returns>
        string GetHomeTopLogin();
        /// <summary>
        /// 是否首页隐藏TopLogin
        /// </summary>
        /// <returns></returns>
        bool GetIsHomeHideTopLogin();
        /// <summary>
        /// 获取HomeCollege
        /// </summary>
        /// <returns></returns>
        string GetHomeCollege();
        /// <summary>
        /// 设备列表仪器名称是否加粗加大
        /// </summary>
        /// <returns></returns>
        bool GetIsShowEquipmentNameCss();
        /// <summary>
        /// 是否必填送样单个样品检测项机时
        /// </summary>
        /// <returns></returns>
        bool GetIsSampleItemUnitUsedHourRequired();
        /// <summary>
        /// 审核用户是否同步水控用户
        /// </summary>
        /// <returns></returns>
        bool GetIsAudiExportSlwUser();
        /// <summary>
        /// 是否显示友情链接（文章列表、文章内页）
        /// </summary>
        /// <returns></returns>
        bool GetIsShowFriendList();
        /// <summary>
        /// 是否预约课题项目必填
        /// </summary>
        /// <returns></returns>
        bool GetIsAppointmentSubjectProjectRequired();
        /// <summary>
        /// 设备资产编号显示
        /// </summary>
        /// <returns></returns>
        string GetLabelShowName();
        /// <summary>
        /// 首页统计未审核用户是否统计中间库导入用户
        /// </summary>
        /// <returns></returns>
        bool GetIsShowImportAuditUser();
        /// <summary>
        /// 前台-平台简介页面分类查看项
        /// </summary>
        /// <returns></returns>
        string GetArticleCategoryShowList();
        /// <summary>
        /// 预约使用性质是否使用辅助字典设置
        /// </summary>
        /// <returns></returns>
        bool GetIsUseNatureFromDictcode();
        /// <summary>
        /// 申请共享基金后是否弹出提示框
        /// </summary>
        /// <returns></returns>
        bool GetIsShowMessageShareFunApply();
        /// <summary>
        /// sj3编辑后跳转
        /// </summary>
        /// <returns></returns>
        bool GetIsToSystemSJ3Index();
        /// <summary>
        /// 显示在线考试系统相关特殊设置
        /// </summary>
        /// <returns></returns>
        bool GetIsShowExaminationSystemSpecialRelativeInfo();
        /// <summary>
        /// 在线考试系统名称
        /// </summary>
        /// <returns></returns>
        string GetExaminationSystemName();
        /// <summary>
        /// 预约过时是否可以审核
        /// </summary>
        /// <returns></returns>
        bool GetIsCheckAppointmentCancelTime();

    }
}
