var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "yyyyMMdd",
            "fulldayshow": "yyyy年M月d日",
            "fulldayvalue": "yyyy-M-d",
            "Md": "M/d (W)",
            "Md3": "M月d日",
            "AM": "上午",
            "PM": "下午",
            "separator": "-",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d日",
            "sun": "周日",
            "mon": "周一",
            "tue": "周二",
            "wed": "周三",
            "thu": "周四",
            "fri": "周五",
            "sat": "周六",
            "jan": "一月",
            "feb": "二月",
            "mar": "三月",
            "apr": "四月",
            "may": "五月",
            "jun": "六月",
            "jul": "七月",
            "aug": "八月",
            "sep": "九月",
            "oct": "十月",
            "nov": "十一月",
            "dec": "十二月"
        },
        "no_implemented": "没有实现",
        "to_date_view": "点击转到该日期的日视图",
        "i_undefined": "未设置",
        "allday_event": "全天预约",
        "repeat_event": "预约",
        "time": "时  间",
        "event": "信  息",
        "location": "仪  器",
        "participant": "预约人",
        "get_data_exception": "获取数据发生异常",
        "new_event": "新预约",
        "confirm_delete_event": "确定删除该预约吗? ",
        "confrim_delete_event_or_all": "删除此序列还是单个事件？\r\n点击[确定]删除事件,点击[取消]删除序列",
        "data_format_error": "数据格式错误！ ",
        "invalid_title": "预约标题不能为空且不能包含符号($<>)",
        "view_no_ready": "视图未准备就绪",
        "example": "例如：预约使用记录",
        "content": "内 容",
        "create_event": "创建预约",
        "update_detail": "修改预约详细信息",
        "click_to_detail": "点击查看详细",
        "i_delete": "删除",
        "day_plural": "天",
        "others": "另外",
        "item": "个"
    }
});
